# The public documentation URL, used for sitemap.xml
url: "http://docs.telerik.com/devtools/xamarin"

# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock]
navigation:
## List your directory names and order here, like this:

    installation-and-deployment:
        title: "Installation and Deployment"
        position: 2
    controls:
        title: "Controls"
        position: 3
    controls/chart:
        title: "Chart"
        position: 4
    controls/calendar:
        title: "Calendar"
        position: 5
    controls/chart/types:
        title: "Types"
        position: 4
    controls/chart/axes:
        title: "Axes"
        position: 5
    controls/chart/series:
        title: "Series"
        position: 6
    controls/chart/behaviors:
        title: "Behaviors"
        position: 7
    controls/chart/how-to:
        title: "How To"
        position: 10
    controls/chart/series/cartesian:
        title: "CartesianSeries"
        position: 2
    controls/chart/series/pie:
        title: "PieSeries"
        position: 3
    controls/chart/series/cartesian/features:
        title: "Features"
        position: 11
    controls/calendar/features:
        title: "Features"
        position: 4
    controls/calendar/how-to:
        title: "How To"
        position: 5

## The application virtual path
baseurl: "/devtools/xamarin"

## The product name
productName: "Telerik UI for Xamarin Forms"

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:eblhnfskwrk'

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
